PDFLocation: F:\JAVA\Eclipse workspaces\Spring Boot Projects\Documents And Reports\PDF Document Flight Reservation\ReservationDetails
server:
  servlet:
    context-path: /flightreservation
    
logging:
  level:
    net.sf.ehcache: debug
    
    
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/reservation
    username: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
    

    properties:                
               javax:
                     persistence:
                                 sharedCache:
                                             mode: ENABLE_SELECTIVE
                     
               hibernate:
                         generate_statistics: true
                         format_sql: true
                         cache:
                               use_second_level_cache: true
                               region:
                                      factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
                                      
 
                               
 
  mail:
    host: "smtp.gmail.com\t"
    password: indevour
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: kumbharrohit7590
    
    
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
