PDFLocation: F:\JAVA\Eclipse workspaces\Spring Boot Projects\Documents And Reports\PDF Document Flight Reservation\ReservationDetails
server:
  servlet:
    context-path: /flightreservation
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/reservation
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: "smtp.gmail.com\t"
    password: indevour
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: kumbharrohit7590
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
